name: CI

on:
  push:
    branches: [ main, master, "001-*" ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Run Dissector Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v12

      - name: Run Nix Flake Checks
        run: nix flake check
